version: '2'
services:
  rpc:
    build:
      context: ./
      dockerfile: rpc.Dockerfile
    ports:
      - 8545

  workspace:
    build:
      context: ./
      dockerfile: workspace.Dockerfile
    tty: true
    env_file:
        - .env
    volumes:
      - ./:/usr/src/workspace
    links:
      - komodod-etomic

  komodod-etomic:
    image: artempikulin/komodod-etomic
    ports:
      - 10271
    volumes:
      - ~/.zcash-params:/root/.zcash-params
      - ~/.komodo:/root/.komodo
