version: '2'
services:

  rpc:
    image: jincort/blockchain-ethereum-testrpc:latest
    build:
      context: ./
      dockerfile: rpc.Dockerfile
    ports:
      - 8545

  workspace:
    image: jincort/blockchain-sc-workspace:latest
    build:
      context: ./
      dockerfile: workspace.Dockerfile
    tty: true
    volumes:
      - ./:/usr/src/workspace
